### ISSUE TITLE
What's the support state for Intel CPU with AMX and Nvidia GPU with tensor cores?

### ISSUE THREAD

**Issue by hangfu-guo** [ProjectPhysX/OpenCL-Benchmark#16]
Hi, appreciate this benchmark tool!

Just wondering if the results utilize the latest AI acceleration techs in different products.
Since I saw the FLOPS/OPS could be much lower than what we can see from the NV websites.
(For examble, INT8 TOPS).

Can someone please clarify what the results are based on? 

And i know barely nothing about OpenCL, but does the results of FLOPS/OPS align with the theoretical AI capabilities?

**Comment by ProjectPhysX** [comment]
Hi @hangfu-guo,

the benchmark measures only vector arithmetic throughput. This is the performance you get when using the scalar/vector data types `double`/`float`/`half2`/`long`/`int`/`short2`/`char4`. Vector arithmetic is the most general form of GPGPU.
I do not plan to include matrix arithmetic in this benchmark as it is not useful for non-AI HPC nor cross-compatible.

The problem here is that there is no common standards yet for AI hardware, data types, acceleration mechanisms etc. Every vendor does things differently for matrix arithmetic. Nvidia came up with 19-bit ~~TF32~~ TF19 floating-point format because it has convenient hardware implementation, there is no consensus on common FP8 format because different FP8 flavors are better for different AI applications, and then there is the FP4 nonsense ("floating-point" with only 16 different states, two of which are +-0).

Hardware acceleration functions to use any of these non-standard types, or even standard IEEE-754 FP64/FP32/FP16 with matrix acceleration, are completely different between vendors and even between GPU generations from the same vendor. Using Nvidia Tensor Cores is possible in OpenCL, but requires inline PTX assembly; similar for other vendors. That means you have to implement 3 different codes for 3 vendors, and if a 4th vendor comes along, you need another code or it won't work. Not entirely cross-compatible.

Kind regards,
Moritz
